// Called only by the P08 owned fixture with --p12; all data is synthetic.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {fork}=require('node:child_process'),{once}=require('node:events');
const {isolatedEnvironment}=require('./isolatedProcess');
const {VERSION,PARSER,CHECKS}=require('../../server/handoffAnalysisRules');
module.exports=async function({pool,repo,session,record,full,different,post,body,get,output,check}){
  const db=await pool.getConnection();try{await require('../../server/analysisRunMigration').applyAnalysisRuns(db);await require('../../server/analysisQueueMigration').applyAnalysisQueue(db);}finally{db.release();}
  const c=pool.pool.config.connectionConfig,env=isolatedEnvironment({MYSQL_HOST:c.host,MYSQL_PORT:String(c.port),MYSQL_USER:c.user,MYSQL_PASSWORD:c.password,MYSQL_DATABASE:c.database});
  const child=fork(path.resolve(__dirname,'../analysis-worker.js'),['start','--target',`${c.host}:${c.port}/${c.database}`],{env,silent:true,windowsHide:true,execArgv:[]}),events=[];
  child.stdout.on('data',data=>{for(const line of String(data).trim().split('\n'))try{events.push(JSON.parse(line));}catch{}});
  const save=(n,v)=>fs.writeFileSync(path.join(output,'p12-'+n+'.json'),JSON.stringify(v,null,2));
  async function wait(fn){const end=Date.now()+45000;while(Date.now()<end){const v=await fn();if(v)return v;await new Promise(r=>setTimeout(r,50));}throw Error('P12_TIMEOUT');}
  async function execute(h,extra={}){const r=await repo.createAnalysisRun(session,{request_id:crypto.randomUUID(),inputs:[{input_key:'handoff',kind:'handoff',ref_id:h.handoff_version_id}],check_scope:{description:'合成固定交接核对',check_ids:CHECKS},rule_version:VERSION,parser_versions:{[PARSER]:VERSION},steps:[{step_key:'handoff',input_keys:['handoff'],check_ids:CHECKS,parser_key:PARSER}],...extra});await repo.enqueueAnalysis(session,{request_id:crypto.randomUUID(),run_id:r.run_id,policy:{lease_ms:5000,timeout_ms:30000}});return wait(async()=>{const x=await repo.getAnalysisRun(session,r.run_id);return ['partial','failed','succeeded'].includes(x.status)?x:null;});}
  try{
    await wait(()=>events.some(e=>e.event==='worker_started'));
    let first;
    await check('P12 independent worker stores fixed two-end evidence and explicit uncovered scope',async()=>{first=await execute(record);assert.equal(first.status,'partial');assert(first.attempts[0].findings.every(f=>f.finding_type==='not_covered'&&f.verification_status==='pending_verification'&&f.issue_id===null));assert(first.attempts[0].evidence.some(e=>e.locator==='/source'));assert(first.attempts[0].evidence.some(e=>e.locator==='/target'));assert(first.coverage[0].missing.includes('handoff.chain'));save('normal',first);});
    await check('P12 rerun stable identity and result digest',async()=>{const second=await execute(record,{rerun_of_run_id:first.run_id});assert.equal(first.attempts[0].result_digest,second.attempts[0].result_digest);assert.deepEqual(first.attempts[0].findings.map(f=>f.comparison_key),second.attempts[0].findings.map(f=>f.comparison_key));save('rerun',second);});
    await check('P12 unconfirmed missing mapping and scaled units remain questions',async()=>{const d=structuredClone(full);d.claim_status='analysis_pending';d.target=null;d.pairs=[];d.evidence=d.evidence.filter(e=>e.side==='source');const r=await execute(await post(body(d)));assert(r.attempts[0].findings.some(f=>f.rule_id==='handoff.fields'));assert(r.attempts[0].findings.some(f=>f.rule_id==='handoff.confirmation'));save('missing',r);const unit=structuredClone(full);unit.pairs[0].checks.unit={mode:'convert',rule:'千件乘1000转为件',basis:'合成单位表'};const u=await execute(await post(body(unit)));assert(!u.attempts[0].findings.some(f=>f.finding_type==='definite_defect'));save('units',u);});
    await check('P12 scope, stale identity, corrupted fixed source rejected; history preserved',async()=>{await assert.rejects(repo.getAnalysisRun({personId:86,accountId:186,authVersion:1},first.run_id),e=>e.code==='DEFINITION_ACCESS_DENIED');await assert.rejects(repo.getAnalysisRun({...session,authVersion:999},first.run_id),e=>e.code==='DEFINITION_AUTH_REQUIRED');await get('/'+record.handoff_id,'outsider',403);const [[row]]=await pool.execute('SELECT snapshot_json FROM data_map_design_handoff_versions WHERE handoff_version_id=?',[record.handoff_version_id]);await pool.execute("UPDATE data_map_design_handoff_versions SET snapshot_digest=REPEAT('0',64) WHERE handoff_version_id=?",[record.handoff_version_id]);try{await assert.rejects(repo.getAnalysisRun(session,first.run_id));}finally{const {digest,parse}=require('../../server/dataMapDefinitionValues');await pool.execute('UPDATE data_map_design_handoff_versions SET snapshot_digest=? WHERE handoff_version_id=?',[digest(parse(row.snapshot_json)),record.handoff_version_id]);}assert.deepEqual(await repo.getAnalysisRun(session,first.run_id),first);});
    await check('P12 fixed format and enum conflict retains both endpoint definitions',async()=>{const d=structuredClone(full);d.claim_status='analysis_pending';d.identifier_kind='single';d.target.mapping_version_id=different.om.mapping_version_id;d.pairs=[{...d.pairs[0],target_mapping_version_id:different.fm[0].mapping_version_id}];const h=await post(body(d)),r=await execute(h);assert(r.attempts[0].findings.some(f=>f.finding_type==='definite_defect'&&f.rule_id==='handoff.format'));assert(r.attempts[0].findings.some(f=>f.finding_type==='definite_defect'&&f.rule_id==='handoff.enum'));save('defect-handoff',h);save('defect',r);});
    save('results',{passed:true,real_worker:true});
  }finally{if(child.exitCode===null&&child.signalCode===null){const exited=once(child,'exit');child.send('stop');const timer=setTimeout(()=>child.kill('SIGKILL'),10000);await exited;clearTimeout(timer);}save('worker-events',events);save('cleanup',{child_stopped:child.exitCode!==null||child.signalCode!==null});}
};
