// P09 additive storage only. No worker, startup DDL or formal issue writes.
const MIGRATION_KEY = '2026-09-17-analysis-runs-v1';
const definitions = {
  data_map_analysis_runs: `
  run_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  rerun_of_run_id BIGINT NULL,
  manifest_json JSON NOT NULL,
  manifest_digest CHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL,
  revision_no INT NOT NULL,
  created_by_person_id BIGINT NOT NULL,
  scope_department_id BIGINT NOT NULL,
  created_at DATETIME(3) NOT NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  INDEX fk_dm_analysis_parent (rerun_of_run_id),
  INDEX fk_dm_analysis_department (scope_department_id),
  CONSTRAINT fk_dm_analysis_parent FOREIGN KEY (rerun_of_run_id) REFERENCES data_map_analysis_runs(run_id),
  CONSTRAINT fk_dm_analysis_department FOREIGN KEY (scope_department_id) REFERENCES departments(id),
  CHECK (revision_no > 0),
  CHECK (status IN ('queued','running','succeeded','partial','failed','cancelled')),
  CHECK ((status IN ('queued','running') AND finished_at IS NULL) OR (status IN ('succeeded','partial','failed','cancelled') AND finished_at IS NOT NULL))`,
  data_map_analysis_inputs: `
  run_id BIGINT NOT NULL,
  input_key VARCHAR(64) NOT NULL,
  source_id BIGINT NULL,
  definition_version_id BIGINT NULL,
  mapping_version_id BIGINT NULL,
  handoff_version_id BIGINT NULL,
  batch_id BIGINT NULL,
  snapshot_json JSON NOT NULL,
  snapshot_digest CHAR(64) NOT NULL,
  PRIMARY KEY (run_id,input_key),
  INDEX fk_dm_ai_source (source_id),
  INDEX fk_dm_ai_definition (definition_version_id),
  INDEX fk_dm_ai_mapping (mapping_version_id),
  INDEX fk_dm_ai_handoff (handoff_version_id),
  INDEX fk_dm_ai_batch (batch_id),
  CONSTRAINT fk_dm_ai_run FOREIGN KEY (run_id) REFERENCES data_map_analysis_runs(run_id),
  CONSTRAINT fk_dm_ai_source FOREIGN KEY (source_id) REFERENCES data_map_v7_sources(source_id),
  CONSTRAINT fk_dm_ai_definition FOREIGN KEY (definition_version_id) REFERENCES data_map_definition_versions(version_id),
  CONSTRAINT fk_dm_ai_mapping FOREIGN KEY (mapping_version_id) REFERENCES data_map_v7_mapping_versions(mapping_version_id),
  CONSTRAINT fk_dm_ai_handoff FOREIGN KEY (handoff_version_id) REFERENCES data_map_design_handoff_versions(handoff_version_id),
  CONSTRAINT fk_dm_ai_batch FOREIGN KEY (batch_id) REFERENCES data_map_source_files(batch_id),
  CHECK ((source_id IS NOT NULL AND definition_version_id IS NULL AND mapping_version_id IS NULL AND handoff_version_id IS NULL AND batch_id IS NULL) OR
    (source_id IS NULL AND definition_version_id IS NOT NULL AND mapping_version_id IS NULL AND handoff_version_id IS NULL AND batch_id IS NULL) OR
    (source_id IS NULL AND definition_version_id IS NULL AND mapping_version_id IS NOT NULL AND handoff_version_id IS NULL AND batch_id IS NULL) OR
    (source_id IS NULL AND definition_version_id IS NULL AND mapping_version_id IS NULL AND handoff_version_id IS NOT NULL AND batch_id IS NULL) OR
    (source_id IS NULL AND definition_version_id IS NULL AND mapping_version_id IS NULL AND handoff_version_id IS NULL AND batch_id IS NOT NULL))`,
  data_map_analysis_steps: `
  run_id BIGINT NOT NULL,
  step_key VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL,
  attempt_no INT NOT NULL,
  PRIMARY KEY (run_id,step_key),
  CONSTRAINT fk_dm_as_run FOREIGN KEY (run_id) REFERENCES data_map_analysis_runs(run_id),
  CHECK (attempt_no >= 0),
  CHECK (status IN ('queued','running','succeeded','partial','failed','cancelled'))`,
  data_map_analysis_attempts: `
  attempt_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT NOT NULL,
  step_key VARCHAR(64) NOT NULL,
  attempt_no INT NOT NULL,
  status VARCHAR(16) NOT NULL,
  coverage_json JSON NULL,
  error_code VARCHAR(64) NULL,
  result_digest CHAR(64) NULL,
  actor_person_id BIGINT NOT NULL,
  completed_by_person_id BIGINT NULL,
  started_at DATETIME(3) NOT NULL,
  finished_at DATETIME(3) NULL,
  UNIQUE KEY uq_dm_aa_attempt (run_id,step_key,attempt_no),
  UNIQUE KEY uq_dm_aa_run (run_id,attempt_id),
  CONSTRAINT fk_dm_aa_step FOREIGN KEY (run_id,step_key) REFERENCES data_map_analysis_steps(run_id,step_key),
  CHECK (attempt_no > 0),
  CHECK (status IN ('running','succeeded','partial','failed','cancelled')),
  CHECK ((status = 'running' AND finished_at IS NULL AND completed_by_person_id IS NULL AND result_digest IS NULL AND coverage_json IS NULL) OR (status <> 'running' AND finished_at IS NOT NULL AND completed_by_person_id IS NOT NULL AND result_digest IS NOT NULL AND coverage_json IS NOT NULL))`,
  data_map_analysis_evidence: `
  evidence_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT NOT NULL,
  attempt_id BIGINT NOT NULL,
  evidence_key VARCHAR(64) NOT NULL,
  input_key VARCHAR(64) NOT NULL,
  snapshot_json JSON NOT NULL,
  snapshot_digest CHAR(64) NOT NULL,
  UNIQUE KEY uq_dm_ae_key (run_id,attempt_id,evidence_key),
  INDEX fk_dm_ae_input (run_id,input_key),
  CONSTRAINT fk_dm_ae_attempt FOREIGN KEY (run_id,attempt_id) REFERENCES data_map_analysis_attempts(run_id,attempt_id),
  CONSTRAINT fk_dm_ae_input FOREIGN KEY (run_id,input_key) REFERENCES data_map_analysis_inputs(run_id,input_key)`,
  data_map_analysis_findings: `
  finding_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT NOT NULL,
  attempt_id BIGINT NOT NULL,
  comparison_key CHAR(64) NOT NULL,
  verification_status VARCHAR(24) NOT NULL,
  issue_id BIGINT NULL,
  snapshot_json JSON NOT NULL,
  snapshot_digest CHAR(64) NOT NULL,
  UNIQUE KEY uq_dm_af_semantic (run_id,attempt_id,comparison_key),
  UNIQUE KEY uq_dm_af_run (run_id,attempt_id,finding_id),
  CONSTRAINT fk_dm_af_attempt FOREIGN KEY (run_id,attempt_id) REFERENCES data_map_analysis_attempts(run_id,attempt_id),
  CHECK (verification_status = 'pending_verification'),
  CHECK (issue_id IS NULL)`,
  data_map_analysis_finding_inputs: `
  run_id BIGINT NOT NULL,
  attempt_id BIGINT NOT NULL,
  finding_id BIGINT NOT NULL,
  input_key VARCHAR(64) NOT NULL,
  PRIMARY KEY (run_id,attempt_id,finding_id,input_key),
  INDEX fk_dm_afi_input (run_id,input_key),
  CONSTRAINT fk_dm_afi_finding FOREIGN KEY (run_id,attempt_id,finding_id) REFERENCES data_map_analysis_findings(run_id,attempt_id,finding_id),
  CONSTRAINT fk_dm_afi_input FOREIGN KEY (run_id,input_key) REFERENCES data_map_analysis_inputs(run_id,input_key)`,
  data_map_analysis_finding_evidence: `
  run_id BIGINT NOT NULL,
  attempt_id BIGINT NOT NULL,
  finding_id BIGINT NOT NULL,
  evidence_key VARCHAR(64) NOT NULL,
  PRIMARY KEY (run_id,attempt_id,finding_id,evidence_key),
  INDEX fk_dm_afe_evidence (run_id,attempt_id,evidence_key),
  CONSTRAINT fk_dm_afe_finding FOREIGN KEY (run_id,attempt_id,finding_id) REFERENCES data_map_analysis_findings(run_id,attempt_id,finding_id),
  CONSTRAINT fk_dm_afe_evidence FOREIGN KEY (run_id,attempt_id,evidence_key) REFERENCES data_map_analysis_evidence(run_id,attempt_id,evidence_key)`
};
const tables = Object.keys(definitions);
const statements = () => Object.entries(definitions).map(([table, body]) => `CREATE TABLE IF NOT EXISTS ${table} (${body}\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`);
module.exports = { MIGRATION_KEY, tables, statements };
