// Additive version/provenance metadata. Stable entity identities stay in the
// existing data_map_objects/data_map_fields tables. Never run DDL on startup.
const MIGRATION_KEY = '2026-09-16-data-map-definitions-v1';
const suffix = ' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci';
const definitions = {
  data_map_definition_versions: `
  version_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  entity_type VARCHAR(16) NOT NULL,
  entity_id BIGINT NOT NULL,
  version_no INT NOT NULL,
  object_version_id BIGINT NULL,
  supersedes_version_id BIGINT NULL,
  schema_version VARCHAR(64) NOT NULL,
  definition_json JSON NOT NULL,
  base_snapshot_json JSON NOT NULL,
  content_digest CHAR(64) NOT NULL,
  base_digest CHAR(64) NOT NULL,
  digest_algorithm VARCHAR(32) NOT NULL,
  source_kind VARCHAR(16) NOT NULL,
  created_by_person_id BIGINT NULL,
  created_at DATETIME(3) NOT NULL,
  UNIQUE KEY uq_dm_definition_sequence (entity_type, entity_id, version_no),
  UNIQUE KEY uq_dm_definition_entity_version (entity_type, entity_id, version_id),
  INDEX fk_dm_definition_parent (object_version_id),
  INDEX fk_dm_definition_previous (supersedes_version_id),
  CONSTRAINT fk_dm_definition_parent FOREIGN KEY (object_version_id) REFERENCES data_map_definition_versions(version_id),
  CONSTRAINT fk_dm_definition_previous FOREIGN KEY (supersedes_version_id) REFERENCES data_map_definition_versions(version_id),
  CHECK (entity_type IN ('object','field')),
  CHECK (source_kind IN ('legacy','manual')),
  CHECK (version_no > 0),
  CHECK (source_kind = 'legacy' OR created_by_person_id IS NOT NULL)`,
  data_map_definition_heads: `
  entity_type VARCHAR(16) NOT NULL,
  entity_id BIGINT NOT NULL,
  current_version_id BIGINT NOT NULL,
  revision_no INT NOT NULL,
  PRIMARY KEY (entity_type, entity_id),
  INDEX fk_dm_definition_head (entity_type, entity_id, current_version_id),
  CONSTRAINT fk_dm_definition_head FOREIGN KEY (entity_type, entity_id, current_version_id) REFERENCES data_map_definition_versions(entity_type, entity_id, version_id),
  CHECK (revision_no > 0)`,
  data_map_definition_events: `
  event_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  version_id BIGINT NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  basis_json JSON NOT NULL,
  actor_person_id BIGINT NOT NULL,
  created_at DATETIME(3) NOT NULL,
  INDEX fk_dm_definition_event_version (version_id),
  CONSTRAINT fk_dm_definition_event_version FOREIGN KEY (version_id) REFERENCES data_map_definition_versions(version_id),
  CHECK (event_type IN ('definition_saved','fact_checked','needs_more_info'))`,
  data_map_source_files: `
  batch_id BIGINT NOT NULL PRIMARY KEY,
  raw_sha256 CHAR(64) NULL,
  raw_digest_status VARCHAR(16) NOT NULL,
  byte_length BIGINT NULL,
  parser_version VARCHAR(64) NOT NULL,
  template_profile_version VARCHAR(64) NOT NULL,
  scope_department_id BIGINT NOT NULL,
  imported_by_person_id BIGINT NOT NULL,
  UNIQUE KEY uq_dm_source_content (raw_sha256, parser_version, template_profile_version, scope_department_id),
  INDEX fk_dm_source_department (scope_department_id),
  CONSTRAINT fk_dm_source_batch FOREIGN KEY (batch_id) REFERENCES data_map_import_batches(id),
  CONSTRAINT fk_dm_source_department FOREIGN KEY (scope_department_id) REFERENCES departments(id),
  CHECK (raw_digest_status IN ('available','unavailable')),
  CHECK ((raw_digest_status = 'available' AND raw_sha256 IS NOT NULL AND byte_length IS NOT NULL) OR (raw_digest_status = 'unavailable' AND raw_sha256 IS NULL AND byte_length IS NULL)),
  CHECK (byte_length IS NULL OR (byte_length >= 0))`,
  data_map_source_cells: `
  cell_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  batch_id BIGINT NOT NULL,
  sheet_name VARCHAR(128) NOT NULL,
  cell_address VARCHAR(16) NOT NULL,
  raw_type VARCHAR(16) NOT NULL,
  raw_value_json JSON NOT NULL,
  UNIQUE KEY uq_dm_source_cell (batch_id, sheet_name, cell_address),
  CONSTRAINT fk_dm_source_cell_batch FOREIGN KEY (batch_id) REFERENCES data_map_source_files(batch_id),
  CHECK (raw_type IN ('blank','string','number','boolean','formula','date'))`,
  data_map_source_mappings: `
  mapping_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  batch_id BIGINT NOT NULL,
  sheet_name VARCHAR(128) NOT NULL,
  record_type VARCHAR(16) NOT NULL,
  local_id VARCHAR(128) NULL,
  source_row INT NOT NULL,
  platform_version_id BIGINT NULL,
  source_cell_ids_json JSON NOT NULL,
  unresolved_reason VARCHAR(255) NULL,
  UNIQUE KEY uq_dm_source_local (batch_id, sheet_name, record_type, local_id),
  UNIQUE KEY uq_dm_source_row (batch_id, sheet_name, record_type, source_row),
  INDEX fk_dm_source_mapping_version (platform_version_id),
  CONSTRAINT fk_dm_source_mapping_batch FOREIGN KEY (batch_id) REFERENCES data_map_source_files(batch_id),
  CONSTRAINT fk_dm_source_mapping_version FOREIGN KEY (platform_version_id) REFERENCES data_map_definition_versions(version_id),
  CHECK (record_type IN ('object','field')),
  CHECK (source_row > 0),
  CHECK ((platform_version_id IS NULL AND unresolved_reason IS NOT NULL) OR (platform_version_id IS NOT NULL AND unresolved_reason IS NULL))`,
  data_map_definition_requests: `
  actor_person_id BIGINT NOT NULL,
  action VARCHAR(32) NOT NULL,
  request_id CHAR(36) NOT NULL,
  scope_department_id BIGINT NOT NULL,
  payload_digest CHAR(64) NOT NULL,
  result_json JSON NULL,
  created_at DATETIME(3) NOT NULL,
  PRIMARY KEY (actor_person_id, action, request_id)`
};
const statements = () => Object.entries(definitions).map(([table, body]) => `CREATE TABLE IF NOT EXISTS ${table} (${body}\n)${suffix}`);
module.exports = { MIGRATION_KEY, statements, tables: Object.keys(definitions) };
