import React, { useEffect, useState } from 'react';
import { StatusPanel } from './components.jsx';
import { IdentityTable as Table, IdentityField as Field } from './IdentityShared.jsx';
const events={account_created:'创建账号',account_activated:'首次启用',account_enabled:'重新启用',account_disabled:'停用账号',account_unlocked:'解锁账号',password_reset:'重置密码',password_changed:'修改密码',department_changed:'变更部门',role_assigned:'授予角色',role_revoked:'撤销角色',login_succeeded:'登录成功'};
export function AccessAudit({api,onLegacy}) {
  const initial=()=>new URLSearchParams(location.search).get('event')||'';
  const [event,setEvent]=useState(initial),[rows,setRows]=useState(null),[error,setError]=useState(null),[revision,setRevision]=useState(0);
  useEffect(()=>{const pop=()=>setEvent(initial());window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop);},[]);
  useEffect(()=>{const controller=new AbortController();setRows(null);setError(null);api.request('/api/org/accounts/audit-events?limit=200'+(event?'&eventType='+encodeURIComponent(event):''),{signal:controller.signal}).then(result=>{if(!controller.signal.aborted)setRows(result);}).catch(e=>{if(!controller.signal.aborted)setError(e);});return()=>controller.abort();},[api,event,revision]);
  return <div className="identity-module"><section className="card"><h2>查看访问审计</h2><p>显示当前条件下最近 200 条账号、密码、部门和角色授权事件。记录数量不代表全部历史；不展示密码或凭据。</p><div className="identity-actions"><button onClick={()=>setRevision(n=>n+1)}>刷新审计</button><a href="/#/rbac" onClick={onLegacy}>原访问审计入口</a></div><Field label="事件类型"><select value={event} onChange={e=>{const url=new URL(location.href);e.target.value?url.searchParams.set('event',e.target.value):url.searchParams.delete('event');history.replaceState(history.state,'',url.pathname+url.search);setEvent(e.target.value);}}><option value="">全部事件</option>{Object.entries(events).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></Field></section>{error?<StatusPanel kind="error" title="访问审计暂不可用" onRetry={()=>setRevision(n=>n+1)}>{error.message}</StatusPanel>:rows?<section className="card" data-audit-ready="true"><Table headers={['时间','事件','操作人','对象','原因或依据','迁移批次']} rows={rows.map(r=>[r.created_at,events[r.event_type]||r.event_type,r.actor_name||'系统',r.target_name||'未提供',r.reason||'未提供',r.migration_batch_id||'不适用'])}/></section>:<StatusPanel kind="loading" title="正在读取访问审计…"/>}</div>;
}
