import React,{useEffect,useRef,useState} from 'react';
import {StatusPanel,useInputProtection} from './components.jsx';
const root='/api/design-handoffs',dims={field:'字段含义',format:'格式',enum:'枚举',unit:'单位',version:'版本'},ops={produce:'产生',use:'使用',modify:'修改',deliver:'交付',receive:'接收'};
const states={material_declared:'材料声明',human_confirmed:'人工确认',analysis_pending:'分析待定'};
const kinds={uploaded_material:'独立材料',preview_revision:'预览修订',published_version:'已发布版本'};
const blank=()=>({title:'',claim_status:'analysis_pending',source:null,target:null,identifier_kind:'unknown',identity_rule:'',identity_basis:'',delivery_condition:'',reception_requirement:'',evidence:[],pairs:[]});
export function DesignHandoffs({api,draft,setDraft}){
  const guard=useInputProtection(),generation=useRef(0),active=useRef(null),first=useRef(null);
  const [cap,setCap]=useState(null),[items,setItems]=useState([]),[next,setNext]=useState(null),[partial,setPartial]=useState(false),[sources,setSources]=useState([]),[sourcesNext,setSourcesNext]=useState(null),[contexts,setContexts]=useState({}),[detail,setDetail]=useState(null),[historyRows,setHistoryRows]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(null),[notice,setNotice]=useState('');
  const allowed=draft&&cap?.can_write&&draft.owner===cap.person_id&&draft.department===cap.department_id;
  const filter=new URLSearchParams(location.search),entity=filter.get('entity_id'),type=filter.get('entity_type');
  function cancel(){generation.current++;active.current?.abort();}
  useEffect(()=>()=>cancel(),[]);
  async function run(fn){cancel();const n=generation.current,c=new AbortController();active.current=c;const valid=()=>n===generation.current&&!c.signal.aborted;setBusy(true);setError(null);try{await fn(c.signal,valid);}catch(e){if(valid()&&e.name!=='AbortError')setError(e);}finally{if(valid())setBusy(false);}}
  async function list(s,v,after=null){const q=new URLSearchParams({...((entity&&type)?{entity_id:entity,entity_type:type}:{}),...(after?{after}:{})});const r=await api.request(root+'?'+q,{signal:s});if(v()){setItems(old=>after?[...old,...r.items]:r.items);setNext(r.next);setPartial(r.partial);}}
  async function read(hid,s,v){const r=await api.request(root+'/'+hid,{signal:s});if(v())setDetail(r);}
  async function sourceList(s,v,after=null){const r=await api.request('/api/v7-mappings/sources'+(after?'?after='+after:''),{signal:s});if(v()){setSources(old=>after?[...old,...r.items]:r.items);setSourcesNext(r.next);if(r.partial)setPartial(true);}}
  function initialize(){run(async(s,v)=>{setCap(null);setContexts({});setDetail(null);setHistoryRows(null);setItems([]);setSources([]);const c=await api.request(root+'/capabilities',{signal:s});await list(s,v);await sourceList(s,v);if(draft?.owner===c.person_id&&draft?.department===c.department_id){const ctx={};for(const side of ['source','target'])if(draft.sourceIds[side])ctx[side]=await api.request(root+'/sources/'+draft.sourceIds[side],{signal:s});if(v())setContexts(ctx);}if(v())setCap(c);const hid=filter.get('handoff');if(hid)await read(hid,s,v);});}
  useEffect(initialize,[]);
  useEffect(()=>{if(allowed)first.current?.focus();},[Boolean(allowed)]);
  function leave(){if(!guard.confirmLeave())return false;cancel();setBusy(false);setDraft(null);setNotice('');return true;}
  function update(key,value){setDraft(d=>({...d,dirty:true,requestId:crypto.randomUUID(),values:{...d.values,[key]:value}}));}
  function begin(r=null){if(!leave())return;setContexts({});setHistoryRows(null);setDraft({owner:cap.person_id,department:cap.department_id,dirty:true,requestId:crypto.randomUUID(),handoffId:r?.handoff_id||null,expected:r?.revision_no||0,sourceIds:{source:r?.source?.source_id||'',target:r?.target?.source_id||''},values:r?structuredClone(r.input):blank()});if(r)run(async(s,v)=>{const ctx={};for(const side of ['source','target'])if(r[side])ctx[side]=await api.request(root+'/sources/'+r[side].source_id,{signal:s});if(v())setContexts(ctx);});}
  function choose(hid){if(!leave())return;setDetail(null);setHistoryRows(null);run(async(s,v)=>{await read(hid,s,v);if(v())history.replaceState(history.state,'','/app/design-handoffs?'+new URLSearchParams({handoff:hid,...(entity?{entity_id:entity,entity_type:type}:{})}));});}
  function chooseSource(side,sid){if(draft.values[side]&&!window.confirm('更换此端来源会清空此端位置选择；已填写的字段对应保留，需要逐项重新核对。是否继续？'))return;run(async(s,v)=>{const ctx=sid?await api.request(root+'/sources/'+sid,{signal:s}):null;if(v()){setContexts(c=>({...c,[side]:ctx}));setDraft(d=>({...d,requestId:crypto.randomUUID(),sourceIds:{...d.sourceIds,[side]:sid},values:{...d.values,[side]:null}}));}});}
  function endpointChange(side,key,value){update(side,{mapping_version_id:'',behavior_ref:'',operations:[],...draft.values[side],[key]:value});}
  function pairChange(index,key,value){update('pairs',draft.values.pairs.map((p,i)=>i===index?{...p,[key]:value}:p));}
  function submit(status){run(async(s,v)=>{const r=await api.request(root,{method:'POST',signal:s,body:{request_id:draft.requestId,handoff_id:draft.handoffId,expected_revision:draft.expected,definition:{...draft.values,claim_status:status}}});if(!v())return;setDraft(null);setNotice(status==='human_confirmed'?'已记录人工设计确认。实际接收和系统同步尚未验证。':'设计关系已保存，待核实项继续保留。');await list(s,v);await read(r.handoff_id,s,v);if(v())history.replaceState(history.state,'','/app/design-handoffs?handoff='+r.handoff_id);});}
  const textarea=(key,label)=> <label className="management-input">{label}<textarea aria-label={label} disabled={busy} value={draft.values[key]||''} maxLength={4096} onChange={e=>update(key,e.target.value)}/></label>;
  function endpointEditor(side){const label=side==='source'?'来源':'目标',ctx=contexts[side],value=draft.values[side];return <fieldset className="handoff-endpoint"><legend>{label}流程与行为</legend>
    <label className="management-input">{label}固定来源<select aria-label={label+'固定来源'} value={draft.sourceIds[side]} disabled={busy} onChange={e=>chooseSource(side,e.target.value)}><option value="">待补充</option>{sources.filter(s=>s.validation_status==='valid').map(s=><option key={s.source_id} value={s.source_id}>来源 {s.source_id} · {kinds[s.source_kind]} · {s.original_name||'固定流程'}</option>)}{draft.sourceIds[side]&&!sources.some(s=>s.source_id===draft.sourceIds[side])&&<option value={draft.sourceIds[side]}>固定来源 {draft.sourceIds[side]}</option>}</select></label>
    {ctx&&<><p>{ctx.process.process_name} · {ctx.process.process_ref}</p><label className="management-input">{label}对象映射<select aria-label={label+'对象映射'} disabled={busy} value={value?.mapping_version_id||''} onChange={e=>endpointChange(side,'mapping_version_id',e.target.value)}><option value="">请选择明确映射</option>{ctx.mappings.filter(m=>!m.local_field_ref).map(m=><option key={m.mapping_version_id} value={m.mapping_version_id}>{m.object_name} · {m.local_object_ref} · 对象 {m.object_id} · 映射版本 {m.mapping_version_id} · {m.effective_confirmed?'已确认':'待核实'}</option>)}{value?.mapping_version_id&&!ctx.mappings.some(m=>m.mapping_version_id===value.mapping_version_id)&&<option value={value.mapping_version_id}>历史映射 {value.mapping_version_id}（需重新核对）</option>}</select></label>
    <label className="management-input">{label}行为<select aria-label={label+'行为'} disabled={busy} value={value?.behavior_ref||''} onChange={e=>endpointChange(side,'behavior_ref',e.target.value)}><option value="">请选择行为</option>{ctx.behaviors.map(b=><option value={b.behavior_ref} key={b.behavior_ref}>{b.behavior_name} · {b.actor_description}</option>)}</select></label><div className="handoff-operations">{Object.entries(ops).map(([key,name])=><label key={key}><input type="checkbox" aria-label={label+name} disabled={busy} checked={value?.operations.includes(key)||false} onChange={e=>endpointChange(side,'operations',e.target.checked?[...(value?.operations||[]),key]:value.operations.filter(k=>k!==key))}/>{name}</label>)}</div></>}
  </fieldset>;}
  const fieldOptions=side=>contexts[side]?.mappings.filter(m=>m.local_field_ref&&m.parent_mapping_version_id===draft.values[side]?.mapping_version_id)||[];
  function endpointView(e,label){return <div className="handoff-endpoint"><h3>{label}</h3>{e?<><strong>{e.process_name} → {e.behavior_name}</strong><p>办理位置：{e.actor_description||'待确认'}</p><p>{e.operations.map(o=>ops[o]).join('、')}「{e.object_name}」· 对象 {e.object_id} · 固定版本 {e.object_version_id}</p><p>{kinds[e.source_kind]} · 流程 {e.process_ref} · 行为 {e.behavior_ref}</p><a href={'/app/v7-mappings?source='+e.source_id}>查看固定来源和映射</a> · <a href={'/app/objects?object='+e.object_id}>查看对象与版本</a></>:<p>来源缺失，待补充。</p>}</div>;}
  return <>
    <section className="card"><h2>设计交接关系</h2><p>查清对象在哪里产生或使用、怎样识别同一对象、交付哪些字段，以及接收条件。所有关系固定绑定来源和台账版本。</p><p className="muted">材料声明、分析待定和人工确认分别保留。此处记录设计关系，实际系统同步和运行接收尚待证据验证。</p>{entity&&<p>当前查看{type==='field'?'字段':'对象'} {entity} 的受影响关系（包含历史修订引用）。</p>}</section>
    {busy&&<StatusPanel kind="loading" title="正在处理设计交接…"/>}{error&&<StatusPanel kind="error" title="设计交接操作未完成" onRetry={initialize}>{error.message} {error.code||''} 原输入与提交修订号已保留。{error.fieldErrors?.design_checks?.length>0&&<span>待核实：{error.fieldErrors.design_checks.join('；')}</span>}</StatusPanel>}{notice&&<StatusPanel kind="success" title={notice}/>}
    {draft&&!allowed&&<StatusPanel title="输入已保留，正在核对当前身份与两端范围">身份或依赖恢复后可继续；不会自动保存。<button className="secondary" onClick={()=>{if(leave())initialize();}}>放弃先前输入</button></StatusPanel>}
    <div className="management-layout"><section className="card management-list"><h2>交接清单</h2>{cap?.can_write&&!draft&&<button className="primary" disabled={busy} onClick={()=>begin()}>新增设计交接关系</button>}<button className="secondary" disabled={busy} onClick={initialize}>查看最新关系</button>{partial&&<p>部分来源暂不可用，当前结果不完整，请恢复后重试。</p>}<ul className="field-list">{items.map(r=><li key={r.handoff_id}><button className="text-button handoff-choice" onClick={()=>choose(r.handoff_id)}>交接 {r.handoff_id} · {r.title} · {states[r.claim_status]}{r.issues.length?' · 待核实 '+r.issues.length+' 项':''}</button></li>)}</ul>{!items.length&&!busy&&<p>当前范围没有可查看的交接关系。</p>}{next&&<button className="secondary" disabled={busy} onClick={()=>run((s,v)=>list(s,v,next))}>载入更多交接</button>}</section>
    <section className="management-main">
    {allowed&&<form className="card v7-form" onSubmit={e=>{e.preventDefault();submit(draft.values.claim_status==='human_confirmed'?'analysis_pending':draft.values.claim_status);}}><h2>{draft.handoffId?'修订设计交接':'建立一条设计交接'}</h2><p className="input-notice">输入尚未保存。原修订 {draft.expected}；修改两端后请逐项核对原字段对应。</p><fieldset disabled={busy} className="handoff-form-body">
      <label className="management-input">交接名称<input ref={first} aria-label="交接名称" value={draft.values.title} maxLength={255} onChange={e=>update('title',e.target.value)}/></label>
      <div className="handoff-endpoints">{endpointEditor('source')}{endpointEditor('target')}</div>{sourcesNext&&<button type="button" className="secondary" onClick={()=>run((s,v)=>sourceList(s,v,sourcesNext))}>载入更多固定来源</button>}
      <h3>如何识别同一对象</h3><label className="management-input">标识类型<select aria-label="标识类型" value={draft.values.identifier_kind} onChange={e=>update('identifier_kind',e.target.value)}><option value="unknown">待确认</option><option value="single">单字段唯一标识</option><option value="composite">组合唯一标识</option></select></label>{textarea('identity_rule','两端标识对应规则')}{textarea('identity_basis','标识核对依据')}
      <h3>两端字段及转换</h3>{draft.values.pairs.map((p,index)=><fieldset className="handoff-pair" key={index}><legend>字段对应 {index+1}</legend>{['source','target'].map(side=>{const key=side+'_mapping_version_id',label=(side==='source'?'来源':'目标')+'字段 '+(index+1),options=fieldOptions(side);return <label className="management-input" key={side}>{label}<select aria-label={label} value={p[key]} onChange={e=>pairChange(index,key,e.target.value)}><option value="">请选择固定字段映射</option>{options.map(m=><option value={m.mapping_version_id} key={m.mapping_version_id}>{m.field_name} · 字段 {m.field_id} · 固定版本 {m.field_version_id} · {m.effective_confirmed?'已确认':'待核实'}</option>)}{p[key]&&!options.some(o=>o.mapping_version_id===p[key])&&<option value={p[key]}>原字段映射 {p[key]}（需重新核对）</option>}</select></label>;})}<label><input type="checkbox" aria-label={'标识字段 '+(index+1)} checked={p.identifier} onChange={e=>pairChange(index,'identifier',e.target.checked)}/>参与唯一标识（组合顺序按字段对应顺序）</label>
      <details><summary>字段、格式、枚举、单位和版本核对</summary>{Object.entries(dims).map(([dim,name])=>{const c=p.checks[dim],change=(key,value)=>pairChange(index,'checks',{...p.checks,[dim]:{...c,[key]:value}});return <div className="definition-group" key={dim}><label className="management-input">{name}对应<select aria-label={name+'对应 '+(index+1)} value={c.mode} onChange={e=>change('mode',e.target.value)}><option value="pending">待核实</option><option value="same">无需转换</option><option value="convert">需要转换</option></select></label><label className="management-input">{name}转换规则<textarea aria-label={name+'转换规则 '+(index+1)} value={c.rule} maxLength={4096} onChange={e=>change('rule',e.target.value)}/></label><label className="management-input">{name}核对依据<textarea aria-label={name+'核对依据 '+(index+1)} value={c.basis} maxLength={4096} onChange={e=>change('basis',e.target.value)}/></label></div>;})}</details><button type="button" className="secondary" onClick={()=>{if(window.confirm('移除此字段对应及已填转换说明？'))update('pairs',draft.values.pairs.filter((_,i)=>i!==index));}}>移除此字段对应</button></fieldset>)}
      <button className="secondary" type="button" disabled={!draft.values.source?.mapping_version_id||!draft.values.target?.mapping_version_id||draft.values.pairs.length>=32} onClick={()=>{update('pairs',[...draft.values.pairs,{source_mapping_version_id:'',target_mapping_version_id:'',identifier:false,checks:Object.fromEntries(Object.keys(dims).map(k=>[k,{mode:'pending',rule:'',basis:''}]))}]);setTimeout(()=>document.querySelector(`[aria-label="来源字段 ${draft.values.pairs.length+1}"]`)?.focus(),0);}}>新增当前交接字段对应</button>
      <h3>交付与接收条件</h3>{textarea('delivery_condition','交付条件')}{textarea('reception_requirement','接收要求')}
      <h3>来源证据</h3>{['source','target'].map(side=>{const e=draft.values.evidence.find(e=>e.side===side)||{side,locator:'',note:''},label=side==='source'?'来源':'目标';const change=(key,value)=>update('evidence',[...draft.values.evidence.filter(e=>e.side!==side),{...e,[key]:value}]);return <div key={side}><label className="management-input">{label}证据位置<input aria-label={label+'证据位置'} value={e.locator} maxLength={1024} onChange={x=>change('locator',x.target.value)}/></label><label className="management-input">{label}证据说明<textarea aria-label={label+'证据说明'} value={e.note} maxLength={4096} onChange={x=>change('note',x.target.value)}/></label></div>;})}
      <label className="management-input">保存状态<select aria-label="保存状态" value={draft.values.claim_status==='human_confirmed'?'analysis_pending':draft.values.claim_status} onChange={e=>update('claim_status',e.target.value)}><option value="analysis_pending">分析待定</option><option value="material_declared">材料声明</option></select></label><div className="import-actions"><button className="secondary">保存设计关系</button><button type="button" className="primary" onClick={()=>submit('human_confirmed')}>人工确认设计关系</button><button type="button" className="secondary" onClick={leave}>取消本次输入</button></div>
    </fieldset></form>}
    {detail&&!draft&&<section className="card"><h2>{detail.title}</h2><p>交接 {detail.handoff_id} · 修订 {detail.revision_no} · {states[detail.claim_status]} · {detail.actor_name||detail.actor_person_id} · {detail.created_at}</p><div className="handoff-endpoints">{endpointView(detail.source,'从哪里交付')}{endpointView(detail.target,'交给谁接收')}</div><h3>如何识别同一对象</h3><p>{detail.identifier_kind==='composite'?'组合标识':detail.identifier_kind==='single'?'单字段标识':'标识待确认'}：{detail.identity_rule||'对应规则待补'}；依据：{detail.identity_basis||'待补'}</p><h3>交付与接收</h3><p>交付条件：{detail.delivery_condition||'待补'}</p><p>接收要求：{detail.reception_requirement||'待补'}</p><h3>交接字段</h3>{detail.pairs.map((p,i)=><div className="definition-group" key={i}><strong>{p.source.name}（版本 {p.source.field_version_id}）→ {p.target.name}（版本 {p.target.field_version_id}）{p.identifier?' · 标识字段':''}</strong><p>目标必填：{p.target.definition.required===null?'待确认':p.target.definition.required?'是':'否'} · <a href={'/api/data-map-definitions/version/'+p.source.field_version_id} target="_blank" rel="noreferrer">来源字段固定版本</a> · <a href={'/api/data-map-definitions/version/'+p.target.field_version_id} target="_blank" rel="noreferrer">目标字段固定版本</a></p>{Object.entries(dims).map(([dim,name])=><p key={dim}>{name}：{p.checks[dim].mode==='convert'?'转换':p.checks[dim].mode==='same'?'无需转换':'待核实'} · {p.checks[dim].rule||'—'} · 依据：{p.checks[dim].basis||'待补'}</p>)}</div>)}<h3>来源证据</h3>{detail.evidence.map((e,i)=><p key={i}>{e.side==='source'?'来源':'目标'}：{e.locator} · {e.note}</p>)}<h3>待核实项</h3>{detail.issues.length?<ul>{detail.issues.map((i,n)=><li key={n}>{i.message}（{i.location}）</li>)}</ul>:<p>本条设计关系的登记项已满足；实际运行接收尚未验证。</p>}<div className="import-actions">{cap?.can_write&&<button className="primary" onClick={()=>begin(detail)}>修订设计交接</button>}<button className="secondary" onClick={()=>run(async(s,v)=>{const r=await api.request(root+'/'+detail.handoff_id+'/history',{signal:s});if(v())setHistoryRows(r);})}>查看交接历史</button></div></section>}
    {historyRows&&!draft&&<section className="card"><h2>交接修订历史</h2>{historyRows.items.map(r=><p key={r.handoff_version_id}>修订 {r.revision_no} · {states[r.claim_status]} · {r.actor_name||r.actor_person_id} · {r.created_at} · <a href={root+'/'+r.handoff_id+'?version='+r.handoff_version_id} target="_blank" rel="noreferrer">查看固定历史与字段依据</a></p>)}{historyRows.next&&<button className="secondary" onClick={()=>run(async(s,v)=>{const r=await api.request(root+'/'+detail.handoff_id+'/history?before='+historyRows.next,{signal:s});if(v())setHistoryRows(old=>({items:[...old.items,...r.items],next:r.next}));})}>载入更早交接</button>}</section>}
    </section></div>
  </>;
}
