import React,{useEffect,useRef,useState} from 'react';
import {StatusPanel,useInputProtection} from './components.jsx';
const root='/api/v7-mappings',defs='/api/data-map-definitions';
const kindName=k=>({uploaded_material:'独立上传材料',preview_revision:'预览固定修订',published_version:'已发布固定版本'}[k]);
const referenceLabel=r=>r.source_kind==='uploaded_material'?'材料批次 '+r.source_ref.batch_id+' · 版本 '+r.source_ref.material_version:r.source_kind==='preview_revision'?'案例 '+r.source_ref.case_id+' · 固定修订 '+r.source_ref.revision_id:'已发布流程版本 '+r.source_ref.process_version_id;
const validationName=s=>({valid:'校验通过',parse_failed:'JSON 解析失败',validation_failed:'V7 校验失败'}[s]);
export function V7Mappings({api,draft,setDraft}){
  const guard=useInputProtection(),generation=useRef(0),active=useRef(null),first=useRef(null);
  const [cap,setCap]=useState(null),[items,setItems]=useState([]),[next,setNext]=useState(null),[partial,setPartial]=useState(false),[detail,setDetail]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(null),[notice,setNotice]=useState(''),[evidence,setEvidence]=useState(null),[historyRows,setHistoryRows]=useState(null);
  const matching=draft&&cap&&draft.owner===cap.person_id&&draft.department===cap.department_id;
  const allowed=matching&&cap.can_write&&(draft.action==='source'||detail?.source_id===draft.sourceId);
  function cancel(){generation.current++;active.current?.abort();}
  useEffect(()=>()=>cancel(),[]);
  async function run(fn){cancel();const n=generation.current,c=new AbortController();active.current=c;const valid=()=>n===generation.current&&!c.signal.aborted;setBusy(true);setError(null);try{await fn(c.signal,valid);}catch(e){if(valid()&&e.name!=='AbortError')setError(e);}finally{if(valid())setBusy(false);}}
  async function list(s,v,after=null){const r=await api.request(root+'/sources'+(after?'?after='+after:''),{signal:s});if(v()){setItems(old=>after?[...old,...r.items]:r.items);setNext(r.next);setPartial(r.partial);}}
  async function read(id,s,v){const r=await api.request(root+'/sources/'+id,{signal:s});if(v())setDetail(r);}
  function initialize(){run(async(s,v)=>{setDetail(null);setEvidence(null);setHistoryRows(null);const c=await api.request(root+'/capabilities',{signal:s});if(!v())return;setCap(c);await list(s,v);const same=draft?.owner===c.person_id&&draft?.department===c.department_id;const sid=same?draft.sourceId:new URLSearchParams(location.search).get('source');if(sid)await read(sid,s,v);});}
  useEffect(initialize,[]);
  useEffect(()=>{if(allowed)first.current?.focus();},[Boolean(allowed),draft?.action]);
  function leave(){if(!guard.confirmLeave())return false;cancel();setBusy(false);setDraft(null);setNotice('');return true;}
  function choose(id){if(!leave())return;setDetail(null);setEvidence(null);setHistoryRows(null);run(async(s,v)=>{await read(id,s,v);if(v())history.replaceState(history.state,'','/app/v7-mappings?source='+id);});}
  function beginSource(){if(!leave())return;setDraft({owner:cap.person_id,department:cap.department_id,action:'source',dirty:true,requestId:crypto.randomUUID(),values:{kind:'uploaded_material',case_id:'',revision_id:'',process_version_id:''},file:null});}
  function beginMapping(o,f=null){if(!leave())return;const m=detail.mappings.find(x=>x.local_object_ref===o.local_object_ref&&x.local_field_ref===(f?.local_field_ref||null));const parent=detail.mappings.find(x=>x.local_object_ref===o.local_object_ref&&!x.local_field_ref);
    setDraft({owner:cap.person_id,department:cap.department_id,action:'mapping',dirty:true,requestId:crypto.randomUUID(),sourceId:detail.source_id,sourceDigest:detail.content_digest,expected:m?.revision_no||0,objectRef:o.local_object_ref,fieldRef:f?.local_field_ref||null,localName:f?.name||o.name,
      values:{object_version_id:m?.object_version_id||parent?.object_version_id||'',field_version_id:m?.field_version_id||'',basis:m?.basis||''},target:null});}
  function update(key,value){setDraft(d=>({...d,dirty:true,requestId:crypto.randomUUID(),target:['object_version_id','field_version_id'].includes(key)?null:d.target,values:{...d.values,[key]:value}}));}
  function lookup(){run(async(s,v)=>{const object=await api.request(defs+'/version/'+encodeURIComponent(draft.values.object_version_id),{signal:s});const field=draft.fieldRef?await api.request(defs+'/version/'+encodeURIComponent(draft.values.field_version_id),{signal:s}):null;if(object.entity_type!=='object'||field&&(field.entity_type!=='field'||field.object_version_id!==object.version_id))throw new Error('所选字段版本必须属于此固定对象版本，请重新核对。');if(v())setDraft(d=>({...d,target:{object,field}}));});}
  function submit(status){run(async(s,v)=>{
    let r;
    if(draft.action==='source'){
      if(draft.values.kind==='uploaded_material'){if(!draft.file)throw new Error('请先选择 V7 JSON 文件。');const body=new FormData();body.append('file',draft.file);body.append('request_id',draft.requestId);r=await api.request(root+'/uploads',{method:'POST',body,signal:s});}
      else{const refs=draft.values.kind==='preview_revision'?{case_id:draft.values.case_id,revision_id:draft.values.revision_id}:{process_version_id:draft.values.process_version_id};r=await api.request(root+'/sources',{method:'POST',body:{request_id:draft.requestId,source_kind:draft.values.kind,...refs},signal:s});}
    }else{
      if(!draft.target)throw new Error('请先读取并核对台账固定版本。');
      r=await api.request(root+'/sources/'+draft.sourceId+'/mappings',{method:'POST',signal:s,body:{request_id:draft.requestId,expected_revision:draft.expected,source_digest:draft.sourceDigest,local_object_ref:draft.objectRef,local_field_ref:draft.fieldRef,object_version_id:draft.target.object.version_id,field_version_id:draft.target.field?.version_id||null,status,basis:draft.values.basis}});r.source_id=draft.sourceId;
    }
    if(!v())return;setDraft(null);setNotice(draft.action==='source'?'来源已登记，请查看校验状态。':status==='candidate'?'映射建议已保存，仍待核实。':'人工映射确认已记录；未作主数据认定。');
    await list(s,v);await read(r.source_id,s,v);if(v())history.replaceState(history.state,'','/app/v7-mappings?source='+r.source_id);
  });}
  function showEvidence(o,f){run(async(s,v)=>{const r=await api.request(root+'/sources/'+detail.source_id+'/evidence?'+new URLSearchParams({object:o.local_object_ref,...(f?{field:f.local_field_ref}:{})}),{signal:s});if(v()){setEvidence(r);setTimeout(()=>document.getElementById('v7-evidence')?.focus(),0);}});}
  const input=(key,label)=> <label className="management-input">{label}<input ref={key==='object_version_id'||key==='case_id'?first:null} aria-label={label} disabled={busy} value={draft.values[key]} onChange={e=>update(key,e.target.value)}/></label>;
  const mappingRow=(o,f=null)=>{const m=detail.mappings.find(x=>x.local_object_ref===o.local_object_ref&&x.local_field_ref===(f?.local_field_ref||null));return <li key={f?.local_field_ref||o.local_object_ref} className="v7-binding"><strong>{f?'字段':'对象'}：{f?.name||o.name||'名称待补'} <small>（{f?.local_field_ref||o.local_object_ref}）</small></strong><p>{m?(m.needs_recheck?'来源或父对象映射已变化，需重新核对':m.status==='confirmed'?'人工映射已确认':'映射建议待核实'):'未映射，待核实'}</p>{m&&<p>台账：{m.field_name||m.object_name} · 稳定 ID {m.field_id||m.object_id} · 固定版本 {m.field_version_id||m.object_version_id} · 映射修订 {m.revision_no}</p>}
    <div className="import-actions"><button className="secondary" disabled={busy} onClick={()=>showEvidence(o,f)}>查看{f?'字段':'对象'}来源证据</button>{m&&<><a className="secondary button-link" href={defs+'/version/'+(m.field_version_id||m.object_version_id)} target="_blank" rel="noreferrer">打开台账固定版本 ↗</a><button className="secondary" disabled={busy} onClick={()=>run(async(s,v)=>{const h=await api.request(root+'/sources/'+detail.source_id+'/mappings/'+m.mapping_id+'/history',{signal:s});if(v())setHistoryRows({...h,mappingId:m.mapping_id});})}>查看映射历史</button></>}{detail.can_write&&!detail.stale&&<button className="primary" disabled={busy} onClick={()=>beginMapping(o,f)}>{m?'修订':'建立'}{f?'字段':'对象'}映射</button>}</div></li>;};
  return <>
    <section className="card"><h2>固定 V7 来源与台账映射</h2><p>先选择独立材料、预览修订或已发布版本，再明确关联对象与字段的固定台账版本。保存建议后仍为待核实；人工确认只确认对应关系。</p><p className="muted">独立材料和预览修订不能作为已发布流程使用。来源登记与映射不会改写 V7 正文或审核记录。</p></section>
    {busy&&<StatusPanel kind="loading" title="正在处理 V7 映射…"/>}{error&&<StatusPanel kind="error" title="映射操作未完成" onRetry={initialize}>{error.message} {error.code||''} {error.status===409?'原输入和提交时修订号均已保留。':''}</StatusPanel>}{notice&&<StatusPanel kind="success" title={notice}/>}
    {draft&&!allowed&&cap&&<StatusPanel title="先前输入已保留，当前身份或来源范围无法展示"><button className="secondary" onClick={()=>{if(leave())initialize();}}>放弃先前输入</button></StatusPanel>}
    <div className="management-layout"><section className="card management-list"><h2>固定来源</h2>{cap?.can_write&&!draft&&<button className="primary" onClick={beginSource} disabled={busy}>登记 V7 固定来源</button>}<button className="secondary" onClick={initialize} disabled={busy}>查看最新记录</button><ul className="field-list">{items.map(r=><li key={r.source_id}><button className="text-button v7-source-choice" onClick={()=>choose(r.source_id)}>来源 {r.source_id} · {kindName(r.source_kind)} · {r.original_name||referenceLabel(r)} · {validationName(r.validation_status)}</button></li>)}</ul>{partial&&<p>部分来源入口尚未开启，当前清单不完整。启用条件满足后请重试。</p>}{!items.length&&!busy&&<p>当前没有可查看的固定来源。</p>}{next&&<button className="secondary" disabled={busy} onClick={()=>run((s,v)=>list(s,v,next))}>载入更多来源</button>}</section>
    <section className="management-main">{detail&&<section className="card"><h2>来源 {detail.source_id}：{kindName(detail.source_kind)}</h2><p>{validationName(detail.validation_status)} · {referenceLabel(detail)}</p>{detail.stale&&<StatusPanel kind="error" title="固定来源已变化，映射停止确认">请核查来源完整性；历史映射继续保留。</StatusPanel>}<details><summary>摘要与校验依据</summary><p>内容摘要（{detail.digest_algorithm}）：{detail.content_digest||'不可用'}</p><p>原始字节 SHA-256：{detail.raw_sha256||'不可用：此来源未保留上传原始字节'}</p>{[...detail.current_validation.errors,...detail.current_validation.blocking_issues].map((e,i)=><p key={i}>{e.code||e.field||e.path}：{e.message}</p>)}</details>{!detail.nodes.length&&<p>没有可映射的有效对象或字段。解析、校验失败的材料不能用于映射。</p>}<ul className="v7-bindings">{detail.nodes.map(o=><React.Fragment key={o.local_object_ref}>{mappingRow(o)}{o.fields.map(f=>mappingRow(o,f))}</React.Fragment>)}</ul></section>}
    {allowed&&<form className="card v7-form" onSubmit={e=>{e.preventDefault();submit('candidate');}}><h2>{draft.action==='source'?'登记固定来源':'明确映射：'+draft.localName}</h2><p className="input-notice">输入尚未保存，仅在当前页面保留。</p>{draft.action==='source'?<>
      <label className="management-input">来源类型<select ref={first} aria-label="来源类型" disabled={busy} value={draft.values.kind} onChange={e=>{if(guard.confirmLeave())setDraft(d=>({...d,requestId:crypto.randomUUID(),file:null,values:{kind:e.target.value,case_id:'',revision_id:'',process_version_id:''}}));}}><option value="uploaded_material">独立上传材料</option><option value="preview_revision">预览固定修订</option><option value="published_version">已发布固定版本</option></select></label>
      {draft.values.kind==='uploaded_material'?<label className="management-input">V7 JSON 文件<input type="file" accept=".json,application/json" disabled={busy} aria-label="V7 JSON 文件" onChange={e=>{const f=e.target.files?.[0];if(f&&(!draft.file||guard.confirmLeave()))setDraft(d=>({...d,requestId:crypto.randomUUID(),file:f}));e.target.value='';}}/>{draft.file?.name||'尚未选择文件'}</label>:draft.values.kind==='preview_revision'?<>{input('case_id','预览案例 ID')}{input('revision_id','固定修订 ID')}</>:input('process_version_id','已发布流程版本 ID')}<button className="primary" disabled={busy}>登记并校验来源</button>
    </>:<><p>V7 局部对象 {draft.objectRef}{draft.fieldRef?' · 字段 '+draft.fieldRef:''} · 原映射修订 {draft.expected}</p>{input('object_version_id','台账对象固定版本 ID')}{draft.fieldRef&&input('field_version_id','台账字段固定版本 ID')}<button type="button" className="secondary" disabled={busy} onClick={lookup}>读取台账版本</button>{draft.target&&<p>已读取：{draft.target.object.definition.name}（对象 ID {draft.target.object.entity_id}，版本 {draft.target.object.version_id}）{draft.target.field?' / '+draft.target.field.definition.name+'（字段 ID '+draft.target.field.entity_id+'，版本 '+draft.target.field.version_id+'）':''}</p>}<label className="management-input">映射核对依据<textarea aria-label="映射核对依据" disabled={busy} maxLength={4096} value={draft.values.basis} onChange={e=>update('basis',e.target.value)}/></label><div className="import-actions"><button className="secondary" disabled={busy||!draft.target}>保存映射建议</button><button className="primary" type="button" disabled={busy||!draft.target||!detail.can_confirm} onClick={()=>submit('confirmed')}>人工确认映射</button></div></>}
      <button className="secondary" type="button" disabled={busy} onClick={leave}>取消本次输入</button></form>}
    {evidence&&<section className="card" id="v7-evidence" tabIndex={-1}><h2>固定来源证据</h2><p>来源 {evidence.source_id} · 对象 {evidence.local_object_ref} · 字段 {evidence.local_field_ref||'不适用'}</p><pre className="v7-evidence">{JSON.stringify(evidence.evidence,null,2)}</pre></section>}
    {historyRows&&<section className="card"><h2>映射修订历史</h2>{historyRows.items.map(h=><p key={h.mapping_version_id}>修订 {h.revision_no} · {h.status==='confirmed'?'人工映射已确认':'建议待核实'} · {h.actor_name||h.actor_person_id} · {h.created_at} · 对象版本 {h.object_version_id}{h.field_version_id?' / 字段版本 '+h.field_version_id:''} · {h.basis}</p>)}{historyRows.next&&<button className="secondary" disabled={busy} onClick={()=>run(async(s,v)=>{const h=await api.request(root+'/sources/'+detail.source_id+'/mappings/'+historyRows.mappingId+'/history?before='+historyRows.next,{signal:s});if(v())setHistoryRows(old=>({...old,items:[...old.items,...h.items],next:h.next}));})}>载入更早映射</button>}</section>}
    </section></div>
  </>;
}
